// styles/emailStyles.js
export const emailStyles = {
  container: {
    maxWidth: '600px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.05)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  },
  header: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
  },
  headerAccent: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #0f3460 0%, #1a1a2e 100%)',
  },
  headerSuccess: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #0d5c3e 0%, #1a4d3a 100%)',
  },
  headerWarning: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #b45309 0%, #9b2c1d 100%)',
  },
  headerDanger: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'linear-gradient(135deg, #991b1b 0%, #7f1d1d 100%)',
  },
  logo: {
    fontSize: '28px',
    fontWeight: '700',
    letterSpacing: '-0.5px',
    margin: '0 0 8px 0',
  },
  title: {
    color: '#ffffff',
    fontSize: '28px',
    fontWeight: '600',
    margin: 0,
    letterSpacing: '-0.3px',
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: '14px',
    marginTop: '8px',
    marginBottom: 0,
  },
  content: {
    padding: '32px 32px 24px',
  },
  greeting: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#1a1a2e',
    marginBottom: '16px',
    letterSpacing: '-0.2px',
  },
  text: {
    fontSize: '15px',
    lineHeight: '1.6',
    color: '#4a5568',
    marginBottom: '16px',
  },
  textSmall: {
    fontSize: '13px',
    lineHeight: '1.5',
    color: '#718096',
    marginBottom: '12px',
  },
  label: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#718096',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '4px',
  },
  value: {
    fontSize: '16px',
    fontWeight: '500',
    color: '#1a1a2e',
    marginBottom: '16px',
  },
  card: {
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    padding: '20px',
    marginTop: '24px',
    marginBottom: '24px',
    border: '1px solid #e2e8f0',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1a1a2e',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '2px solid #e2e8f0',
  },
  divider: {
    borderColor: '#e2e8f0',
    margin: '24px 0',
  },
  button: {
    backgroundColor: '#0f3460',
    color: '#ffffff',
    padding: '14px 32px',
    textDecoration: 'none',
    borderRadius: '40px',
    display: 'inline-block',
    fontWeight: '500',
    fontSize: '15px',
    textAlign: 'center',
    border: 'none',
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    color: '#0f3460',
    padding: '12px 28px',
    textDecoration: 'none',
    borderRadius: '40px',
    display: 'inline-block',
    fontWeight: '500',
    fontSize: '14px',
    textAlign: 'center',
    border: '2px solid #0f3460',
  },
  footer: {
    padding: '24px 32px',
    textAlign: 'center',
    backgroundColor: '#f8fafc',
    borderTop: '1px solid #e2e8f0',
  },
  footerText: {
    fontSize: '12px',
    color: '#94a3b8',
    marginBottom: '8px',
  },
  badge: {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: '500',
  },
  badgeConfirmed: {
    backgroundColor: '#d1fae5',
    color: '#065f46',
  },
  badgeCancelled: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
  },
  badgeShipped: {
    backgroundColor: '#fed7aa',
    color: '#9b2c1d',
  },
  badgePending: {
    backgroundColor: '#e0e7ff',
    color: '#1e3a8a',
  },
  row: {
    marginBottom: '12px',
  },
};